# Generated by Django 2.0.6 on 2018-07-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busRoute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busstops',
            fields=[
                ('stop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=150)),
                ('stop_lat', models.CharField(blank=True, max_length=20, null=True)),
                ('stop_lon', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'busStops',
                'managed': False,
            },
        ),
    ]
