# Generated by Django 2.0.6 on 2018-07-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busRoute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikestations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_number', models.IntegerField(blank=True, null=True)),
                ('list_name', models.CharField(blank=True, max_length=33, null=True)),
                ('list_address', models.CharField(blank=True, max_length=33, null=True)),
                ('list_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('list_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'bikeStations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Busstops',
            fields=[
                ('stop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=150)),
                ('stop_lat', models.CharField(blank=True, max_length=20, null=True)),
                ('stop_lon', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'busStops',
                'managed': False,
            },
        ),
    ]
