# Generated by Django 2.0.6 on 2018-07-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busRoute', '0002_busstops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikestations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_number', models.IntegerField(blank=True, null=True)),
                ('list_name', models.CharField(blank=True, max_length=33, null=True)),
                ('list_address', models.CharField(blank=True, max_length=33, null=True)),
                ('list_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('list_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'bikeStations',
                'managed': False,
            },
        ),
    ]
