# Generated by Django 2.0.6 on 2018-07-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busRoute', '0002_bikestations_busstops'),
        ('busRoute', '0003_bikestations'),
    ]

    operations = [
    ]
